#!/bin/bash
baseDir="/usr/lib"
java_version="jdk16.0.2"
jdk_version="openjdk-16.0.2"
JAVA_HOME="${baseDir}/jdk-16.0.2"


echo "$baseDir/jdk-8u361-linux-aarch64.tar.gz"
## 자바 버전 체크 해서 현재 존재하는 자바가 있으면 건너뛴다, 만약 java라는 게 없는경우 커맨드가 없다고 출력
if [ -z "java -version | grep 'java version'" ]; then
    wget -P $baseDir https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk8u292-b10/OpenJDK8U-jdk_x64_linux_8u292b10.tar.gz;
    tar -zxvf $baseDir/OpenJDK8U-jdk_x64_linux_8u292b10.tar.gz -C $baseDir;
fi


## 명령어를 만들기 위한 FOR문 
array_1=("grep" "${JAVA_HOME}" "/etc/profile")

CH=""
for val in "${array_1[@]}";
do 
    CH+=" $val"
done


## profile에 등록된 JAVA_HOME 이 있는지 체크 하기 위함 없으면 추가해준다. 
if [ -n "$CH" ]; then
    echo "존재한다"
else 
    echo "export JAVA_HOME=${JAVA_HOME}" >> /etc/profile
fi 


## 등록된 환경변수를 실행한다.
source /etc/profile



