version: "3" 

services:

  pr-jenkins:  #pj-jenkins를 사용하면 에러가 나는데 이유를 모르겠음..
    container_name: pr-jenkins
    user: "root"                 # volume 폴더 젒근 권한 설정
    build: .
    volumes:
      - ./jenkins_home:/var/jenkins_home # jenkins 설치 폴더
    environment: 
      - "JENKINS_OPTS=--httpPort=9909"
    ports:
      - "9909:9909"
      - "50000:50000"



# version: '3'
# services:
#   pj-jenkins:
#     container_name: pj-jenkins
#     build: .

# version: "3"
# services:

#   pj-jenkins:
#     container_name: pj-jenkins
#     user: "root"
#     build: .

    



# version: "3" 
# services:

#   my-jenkins:
#     container_name: my-jenkins
#     user: "root"                 # volume 폴더 젒근 권한 설정
#     # image: jenkins
#     build: .
#     volumes:
#       - ./jenkins_home:/var/jenkins_home # jenkins 설치 폴더
#       # - ./var/run:/var/run:ro              # docker 실행 폴더 공유
#     environment:
#       - TZ=Asia/Seoul                     # jenkins 시간
#     ports:
#       - "18080:8080"                      # jenkins 접속 port
#       - "50000:50000"                     # jenkins agent를 통해 통신 할때 
#     # group_add:
#     #   - ${DOCKER_GROUP}                   # docker 실행을 위한 그룹 추가 